name: CI
on:
  push:
    branches:
      - master # need to filter here so we only deploy when there is a push to master
  # no filters on pull requests, so intentionally left blank
  pull_request: 

jobs:     
  build-site:
    runs-on: ubuntu-latest
    steps:
    
    - name: Check if this is a template commit
      if: github.event_name == 'push'
      uses: actions/github-script@0.5.0
      id: gh
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          async function numcommits(){
             // Get number of commits in the first pagination
             const commits = await github.repos.listCommits({
                                  owner: context.repo.owner,
                                  repo: context.repo.repo,
                                 })
             const n = commits.data.length
             // Evidence of a template commit is the first commit in a repo with the message 'Initial commit'
             const template_bool = (process.env.COMMIT_MSG == 'Initial commit') && (n == 1)
             // Emit output
             console.log(`::set-output name=template_bool::${template_bool}`)
          }
          numcommits()
      env:
         COMMIT_MSG: ${{ github.event.commits[0].message }}

    - name: Copy Repository Contents
      if: ((github.event_name == 'push') && (steps.gh.outputs.template_bool == 'false')) || (github.event_name == 'pull_request')
      uses: actions/checkout@master
      with:
        persist-credentials: false

    - name: convert notebooks and word docs to posts
      if: ((github.event_name == 'push') && (steps.gh.outputs.template_bool == 'false')) || (github.event_name == 'pull_request')
      uses: ./ # use the code in this repo instead of fastai/fastpages@master, for testing.
      with:
        BOOL_SAVE_MARKDOWN: false
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}

    - name: setup directories for Jekyll build
      if: ((github.event_name == 'push') && (steps.gh.outputs.template_bool == 'false')) || (github.event_name == 'pull_request')
      run: |
        rm -rf _site
        sudo chmod -R 777 .

    - name: Jekyll build
      if: ((github.event_name == 'push') && (steps.gh.outputs.template_bool == 'false')) || (github.event_name == 'pull_request')
      uses: docker://jekyll/jekyll
      with:
        args: jekyll build -V

    # only deploy upon a push to master
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      if: (github.event_name == 'push') && (steps.gh.outputs.template_bool == 'false')
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./_site
