name: Setup
on: 
  issues:
    types: [opened, edited]
  issue_comment:

jobs:
  setup:
    # The issue must be created by the issue owner, and if the comment is made in subsequent comment that must also be
    # if: github.event.issue.author_association == 'OWNER' && ( (github.event_name == 'issue_comment' && github.event.comment.author_association == 'OWNER') || (github.event_name == 'issues') )
    runs-on: ubuntu-latest
    steps:
    #   - name: parse-metadata-on-open
    #     if: contains(github.event.issue.body, '/setup') || contains(github.event.comment.body, '/setup')
    #     run: |
    #       echo "Triggered"

    - name: see payload
      run: |
        echo "FULL PAYLOAD:\n${PAYLOAD}\n"
      env:
        PAYLOAD: ${{ toJSON(github.event) }}


# comment is contained in #comment.body


# name: Setup-Open
# on: 
#   issues:
#     types: [opened]


# jobs:
#   setup-open:
#     if: github.event.issue.author_association == 'OWNER' # and github.event
#     runs-on: ubuntu-latest
#     steps:
#       - name: see payload
#         run: |
#           echo "FULL PAYLOAD:\n${PAYLOAD}\n"
#         env:
#           PAYLOAD: ${{ toJSON(github.event) }}
#       - name: print variable
#         run: |
#           echo "event_name: ${PAYLOAD}"
#         env:
#           PAYLOAD: ${{ github.event_name }}