name: issue comment payload
on: 
  issues:
    types: [opened]

jobs:     
  upgrade:
    runs-on: ubuntu-latest
    steps:
        
    - name: see payload
      run: |
        echo "FULL PAYLOAD:\n${PAYLOAD}\n"
        echo "PR_PAYLOAD PAYLOAD:\n${PR_PAYLOAD}"
      env:
        PAYLOAD: ${{ toJSON(github.event) }}
        PR_PAYLOAD: ${{ github.event.pull_request }}
